name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.10"
          - arch: "x64"
            os: "windows-latest"
            version: "1.10"
          - arch: "x64"
            os: "macOS-latest"
            version: "1.10"
          - arch: "x86"
            os: "ubuntu-latest"
            version: "1.10"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.9"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.8"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.7"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.6"
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{runner.os}}-test-${{env.cache-name}}-${{hashFiles('**/Project.toml')}}
          restore-keys: |
            ${{runner.os}}-test-${{env.cache-name}}-
            ${{runner.os}}-test-
            ${{runner.os}}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON:
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: lcov.info
