name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.4"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.5"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.6"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.7"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.8"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "1.9"
          - arch: "x64"
            os: "ubuntu-latest"
            version: "nightly"
          - arch: "x64"
            os: "windows-latest"
            version: "1.9"
          - arch: "x64"
            os: "macOS-latest"
            version: "1.9"
          - arch: "x86"
            os: "ubuntu-latest"
            version: "1.9"
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON:
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: lcov.info
